[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
skill_issue_escrow = "4UCURsRhmvhjaAaHLryWV1Zb4yv5YRo7W8A7ZyXrkUER"

[programs.devnet]
skill_issue_escrow = "8uifDvyerwvrpvjbKsf82SqvYH1YvCoAcbLzNq52TFcr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
